# Assignment 11-12


In [9]:
# Importing the libraries

import torch
import numpy as np

In [2]:
# Tensor initialization

# 1. Directly from data
data=[[10,20],[30,40]]
tensor_data=torch.tensor(data)
print(tensor_data)

# 2. From a NumPy array
numpy_array=np.array(data)
result=torch.from_numpy(numpy_array)
print(result)

tensor([[10, 20],
        [30, 40]])
tensor([[10, 20],
        [30, 40]], dtype=torch.int32)


In [3]:
# Generating the random tensor
random_tensor=torch.rand_like(tensor_data, dtype=torch.float) # overrides the datatype of data
print(f"Random Tensor: \n {random_tensor} \n")

Random Tensor: 
 tensor([[0.1051, 0.2862],
        [0.2863, 0.5422]]) 



In [4]:
# Shape tuple of tensor.
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.7645, 0.7767, 0.8367],
        [0.5751, 0.4302, 0.7203]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
# CUDA is a programming model and computing toolkit developed by NVIDIA.
# It enables you to perform compute-intensive operations faster by parallelizing tasks across GPUs.
# CUDA is the dominant API used for deep learning
# if torch.cuda.is_available():
#   tensor = tensor.to('cuda')
#   print(f"Device tensor is stored on: {tensor.device}")

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(DEVICE)

cpu


In [6]:
# Indexing and slicing.
tensor = torch.ones(5, 5)
tensor[:,2] = 0
print(tensor)

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])


In [7]:
# Joining the tensors
new_tensor=torch.cat([tensor, tensor, tensor], dim=1)
print(new_tensor)

tensor([[1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1.]])


In [8]:
# Multiplying the tensors

# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.],
        [1., 1., 0., 1., 1.]])
